"""Generated by openadapt-flow. Human-readable rendering of
workflow 'mockmed-triage' — for code review only; the replayer
executes workflow.json, not this file."""

WORKFLOW_NAME = 'mockmed-triage'
RECORDING_ID = '3290705d23254d978c7a335776e407ad'
PARAMS = {'note': 'Synthetic follow-up in two weeks'}  # param -> example/default value


def run(flow, params=PARAMS):
    # step_000: click 'Open' [reversible]
    # landmark: 'Action' (above, 51px)
    # landmark: 'Open' (below, 58px)
    # identity: armed via PHI-free salted-hash template (5 band tokens, structured); no patient identifier stored
    flow.click(template='templates/step_000.png', click_point=(775, 186), region=(695, 154, 160, 64), ocr_text='Open')
    # expect region_stable region=(0, 43, 968, 318) phash='f8e083ffbc08383c' (tol 16)
    # expect text_present text='JaneSample—MRNP1—DOB1980-01-01'

    # step_001: click 'New Encounter' [reversible]
    # landmark: 'Encounters' (below, 61px)
    # landmark: 'No encountersyet.' (below, 85px)
    # identity: armed via PHI-free salted-hash template (0 band tokens, structured); no patient identifier stored
    flow.click(template='templates/step_001.png', click_point=(114, 159), region=(34, 127, 160, 64), ocr_text='New Encounter')
    # expect region_stable region=(0, 101, 696, 350) phash='fae0c01e950fc78e' (tol 16)
    # expect text_present text='EncounterType'

    # step_002: click 'Triage' [reversible]
    # landmark: 'Note' (below, 70px)
    # landmark: 'NewEncounter' (above, 77px)
    # identity: armed via PHI-free salted-hash template (0 band tokens, structured); no patient identifier stored
    flow.click(template='templates/step_002.png', click_point=(85, 214), region=(5, 182, 160, 64), ocr_text='Triage')
    # expect region_stable region=(0, 163, 177, 102) phash='88c2f2295d2da73d' (tol 16)

    # step_003: click at (480, 268) [reversible]
    # landmark: 'Consult' (left_of, 279px)
    # landmark: 'JaneSample—MRNP1—DOB1980-01-01' (left_of, 319px)
    # identity: armed via PHI-free salted-hash template (0 band tokens, structured); no patient identifier stored
    flow.click(template='templates/step_003.png', click_point=(480, 268), region=(400, 236, 160, 64))
    # expect region_stable region=(0, 249, 696, 202) phash='ff3fd53f6a002a00' (tol 16)

    # step_004: type <note> [reversible]
    flow.type_text(params['note'])

    # step_005: click 'Save Encounter' [irreversible]
    # landmark: 'Note' (above, 209px)
    # landmark: 'Triage' (above, 248px)
    # identity: armed via PHI-free salted-hash template (0 band tokens, structured); no patient identifier stored
    flow.click(template='templates/step_005.png', click_point=(134, 457), region=(54, 425, 160, 64), ocr_text='Save Encounter')
    # expect region_stable region=(0, 228, 696, 223) phash='e0e0b83b1f87c7c2' (tol 16)
    # expect text_present text='Encounters'
    # effect record_written match={'patient_id': 'p1', 'type': 'Triage', 'source': 'replay', 'key': 'mockmed-triage-p1-v1'} count=1 idempotency_key='mockmed-triage-p1-v1' [irreversible]
    # effect field_equals match={'patient_id': 'p1', 'type': 'Triage', 'source': 'replay', 'key': 'mockmed-triage-p1-v1'} field='note' value='Synthetic follow-up in two weeks' [irreversible]
